server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smarttour_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true