services:
  postgres:
    image: postgres:15
    container_name: smarttour-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarttour_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smarttour_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: smarttour-cache
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: smarttour-ui-db
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  auth-service:
    build: ../backend/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smarttour_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy

  tour-service:
    build: ../backend/tour-service
    container_name: tour-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smarttour_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy

  booking-service:
    build: ../backend/booking-service
    container_name: booking-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smarttour_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: nginx:alpine
    container_name: smarttour-frontend
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - tour-service
      - booking-service